backend:
  name: github
  repo: sabrinabean/service-chine
  branch: main
  # 💡 下面这行是最关键的，必须改成你现在可用的 proxy Workers 地址
  base_url: https://decap-proxy.sabrinabin-fr.workers.dev
  auth_endpoint: /auth

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
